---
# override defaults because:
# - dnf supports natively priority
# - we don't set up priority for repository during provisioning
gitlab_buildpkg_tools__rpm_deps_pkgs:
  - 'gnupg2'

gitlab_buildpkg_tools__rpm_keys:
  - 'https://inverse.ca/downloads/GPG_PUBLIC_KEY'
  - 'https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL'

gitlab_buildpkg_tools__rpm_deps_repos:
  - name: packetfence
    baseurl: 'http://inverse.ca/downloads/PacketFence/RHEL$releasever/{{ pf_minor_release }}/$basearch'
  - name: nodejs
    baseurl: 'https://rpm.nodesource.com/pub_12.x/el/$releasever/$basearch'

gitlab_buildpkg_tools__rpm_enabled_repos:
  - name: 'CentOS-PowerTools.repo'
    id: 'PowerTools'
    enabled: 1

# packages install will occur
# during build dependencies install from SPEC files
gitlab_buildpkg_tools__rpm_pkgs:
  - 'epel-release'  
