---
- name: Install MailHog
  hosts: [ 'service_mailhog' ]
  gather_facts: True
  become: True

  roles:
    - role: geerlingguy.mailhog
      tags: mailhog
      when: lookup("env", "INTEGRATION_TESTS") == 'yes'
