---
- hosts: pfservers
  name: install pf on standalone
  become: True

  roles:
    - role: inverse_inc.packetfence.packetfence_common
      tags: install
    - role: inverse_inc.packetfence.packetfence_install
      tags: install

- hosts: dev
  name: install additionnal stuff for dev machines
  become: True

  roles:
    - role: geerlingguy.nodejs
      vars:
        nodejs_version: "8.x"
      tags: nodejs
      
    - role: inverse_inc.packetfence.packetfence_dev
      tags: dev