---
- name: Configure Wireless Linux
  hosts: wireless
  become: true
  gather_facts: true
  
  collections:
    - inverse_inc.wireless

  pre_tasks:
  - name: wait for SSH available before provisioning
    wait_for_connection:

  roles:
    - role: hostapd
    - role: wpasupplicant
