---
### COMMON PARAMETERS
before_script:
  - unset http_proxy ; unset https_proxy
  - env | grep ^CI_

### STAGES
stages:
  - build_images
  - build_pkg
  - sign
  - publish
  - install

### VARIABLES
variables:
  CIDIR: ci
  PACKERDIR: $CIDIR/packer
  RPM_DIR: rpm
  DEB_DIR: debian
  VAGRANT_DIR: addons/vagrant
  # env variables
  ANSIBLE_FORCE_COLOR: "true"
  ANSIBLE_STDOUT_CALLBACK: yaml

### TEMPLATES
.pfbuild_job:
  stage: build_images
  tags:
    - shell

.build_job:
  stage: build_pkg
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  # only run jobs on schedules *OR* on "stable" refs (for release) *OR* via "Run pipeline"
  only:
    - schedules
    - web
    - /^stable$/
    - /^devel$/
  tags:
    - docker

.rpm_script:
  script:
    - cp $RPM_DIR/.rpmmacros $HOME
    - ci-build-pkg $RPM_DIR

.deb_script:
  script:
    - ./$CIDIR/debian/convert-to-native-package.sh
    - cp $CIDIR/debian/.devscripts $HOME
    - quilt push
    - ci-build-pkg $DEB_DIR
  variables:
    QUILT_PATCHES: $DEB_DIR/patches


### STAGES

#### BUILD_IMAGES JOBS
pfbuild_manual:
  extends: .pfbuild_job
  script:
    - make -e -C $PACKERDIR pfbuild
  # job need to be explicitly started
  # will not block other stages/jobs
  # will not run when we click "Run pipeline"
  when: manual

pfbuild_test:
  extends: .pfbuild_job
  script:
    # remove 'feature/' prefix from branch name
    - export DOCKER_TAG=${CI_COMMIT_REF_NAME#feature/}
    - make -e -C $PACKERDIR pfbuild
  only:
    - /^feature/packer-.*$/

# build a docker image at release
# used to build release packages, maintenance binaries and assets for maintenance
pfbuild_release:
  extends: .pfbuild_job
  variables:
    ANSIBLE_CENTOS_GROUP: stable_centos
    ANSIBLE_DEBIAN_GROUP: stable_debian
    ANSIBLE_RUBYGEMS_GROUP: stable_rubygems
  script:
    # remove 'packetfence-' prefix from tag
    - export PF_VERSION=${CI_COMMIT_TAG#packetfence-}
    - make -e -C $PACKERDIR DOCKER_TAG=$PF_VERSION pfbuild
  only:
    - /^packetfence-.*$/

#### BUILD_PKG JOBS
build_pkg_centos7:
  image: inverseinc/pfbuild-centos-7
  extends:
    - .build_job
    - .rpm_script

build_pkg_debian_stretch:
  image: inverseinc/pfbuild-debian-stretch
  extends:
    - .build_job
    - .deb_script

### SIGN JOBS
sign:
  # only use when executor is docker
  image: buildpkg/debian:stretch
  stage: sign
  script:
    - ci-sign-pkg
  dependencies:
    - build_pkg_centos7
    - build_pkg_debian_stretch
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  only:
    - schedules
    - web
    - /^packetfence-.*$/
    - /^devel$/
  tags:
    - shell

### PUBLISH JOBS
pages:
  # only use when executor is docker
  image: buildpkg/debian:stretch
  stage: publish
  variables:
    PAGES_DIR: public
  environment:
    name: PPA
    url: http://${CI_PROJECT_NAMESPACE}.gitlab.io/
  script:
    - ci-pages-ppa
    - ci-pages-home
    - ci-pages-tree
  dependencies:
    - sign
  artifacts:
    expire_in: 1 day
    paths:
      - public
  only:
    - schedules
    - web
    - /^packetfence-.*$/
    - /^devel$/
  tags:
    - shell
