---
################################################################################
# COMMON PARAMETERS
################################################################################
before_script:
  - unset http_proxy ; unset https_proxy
  - env | grep ^CI_

################################################################################
# STAGES
################################################################################
stages:
  - build_images
  - build_pkg
  - build_maintenance
  - sign
  - publish
  - install
  - upload

################################################################################
# VARIABLES
################################################################################
variables:
  PFBUILD_CENTOS_7_IMG: inverseinc/pfbuild-centos-7
  PFBUILD_DEB_STRETCH_IMG: inverseinc/pfbuild-debian-stretch
  CIDIR: ci
  PACKERDIR: $CIDIR/packer
  RPM_DIR: rpm
  DEB_DIR: debian
  VAGRANT_DIR: addons/vagrant
  # env variables
  ANSIBLE_FORCE_COLOR: "true"
  ANSIBLE_STDOUT_CALLBACK: yaml


################################################################################
# TEMPLATES
################################################################################

########################################
# TRIGGERS
########################################
# triggers for dev jobs (devel and other development branches)
.job_dev_triggers:
  # run jobs on "devel" branch (push, schedules and web)
  # run jobs on any branches/tags via "Run pipeline", except:
  # - vX.X.X tag
  # - maintenance/vX.X.X branches
  only:
    - /^devel$/
    - web
  except:
    - /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/
    - /^maintenance/v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/

# triggers for release jobs
.job_release_triggers:
  # run job on release tag (vX.X.X) (push and web)
  # no schedule on tag
  # exclude branches to avoid trigger when a branch is called vX.X.X
  only:
    - /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/
  except:
    - branches

# common triggers for jobs use for release and dev
.job_dev_and_release_triggers:
  # run jobs on "devel" branch or vX.X.X tag (push, schedules and web)
  # run jobs on any branches/tags via "Run pipeline", except:
  # - maintenance/vX.X.X branches
  only:
    - /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/
    - /^devel$/
    - web
  except:
    - /^maintenance/v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/

# triggers for maintenance jobs
.job_maintenance_triggers:
  # run job on maintenance branches (push, schedules and web)
  # allow on all maintenance branches, push to branches before 9.2 will not trigger
  # because they don't have .gitlab-ci.yml
  only:
    - /^maintenance/v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/

########################################    
# JOBS
########################################
.pfbuild_job:
  stage: build_images
  tags:
    - shell

.build_job:
  stage: build_pkg
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  tags:
    - docker

.maintenance_job:
  stage: build_maintenance
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  tags:
    - docker

.deploy_deb_job:
  stage: upload
  dependencies:
    - sign
  variables:
    #DEPLOY_USER: see GitLab variables
    DEB_DEPLOY_DIR: ${CI_ENVIRONMENT_NAME}
    DEPLOY_UPDATE: "/builds/bin/ci-repo-deploy deb ${CI_ENVIRONMENT_NAME}"
  script:
    - ./$CIDIR/upload/deploy-packages.sh deb
  # run job on runners tag with inverse AND shell
  tags:
    - inverse
    - shell

.deploy_rpm_job:
  stage: upload
  dependencies:
    - sign
  variables:
    #DEPLOY_USER: see GitLab variables
    RPM_DEPLOY_DIR: ${CI_ENVIRONMENT_NAME}
    DEPLOY_SRPMS: "no"
    DEPLOY_UPDATE: "/builds/bin/ci-repo-deploy rpm ${CI_ENVIRONMENT_NAME}"
  script:
    - ./$CIDIR/upload/deploy-packages.sh rpm
  # run job on runners tag with inverse AND shell
  tags:
    - inverse
    - shell

.rpm_script:
  script:
    - cp $RPM_DIR/.rpmmacros $HOME
    - ci-build-pkg $RPM_DIR

.deb_script:
  script:
    - ./$CIDIR/debian/convert-to-native-package.sh
    - cp $CIDIR/debian/.devscripts $HOME
    - quilt push
    - ci-build-pkg $DEB_DIR
  variables:
    QUILT_PATCHES: $DEB_DIR/patches


################################################################################
# STAGES
################################################################################

########################################
# BUILD_IMAGES JOBS
########################################
pfbuild_manual:
  extends: .pfbuild_job
  script:
    - make -e -C $PACKERDIR pfbuild
  # job need to be explicitly started
  # will not block other stages/jobs
  # will not run when we click "Run pipeline"
  when: manual

pfbuild_test:
  extends: .pfbuild_job
  script:
    # remove 'feature/' prefix from branch name
    - export DOCKER_TAG=${CI_COMMIT_REF_NAME#feature/}
    - make -e -C $PACKERDIR pfbuild
  only:
    - /^feature/packer-.*$/

# build a docker image at release
# used to build release packages, maintenance artifacts for maintenance
pfbuild_release:
  extends:
    - .pfbuild_job
    - .job_release_triggers
  variables:
    ANSIBLE_CENTOS_GROUP: stable_centos
    ANSIBLE_DEBIAN_GROUP: stable_debian
    ANSIBLE_RUBYGEMS_GROUP: stable_rubygems
    # prefix release images with maintenance/ to simplify definition of
    # maintenance jobs
    DOCKER_TAG: maintenance/${CI_COMMIT_TAG}
  script:
    - make -e -C $PACKERDIR pfbuild

########################################
#  BUILD_PKG JOBS
########################################
# build_pkg jobs for development
build_pkg_dev_centos_7:
  image: ${PFBUILD_CENTOS_7_IMG}:latest
  extends:
    - .build_job
    - .job_dev_triggers
    - .rpm_script

build_pkg_dev_debian_stretch:
  image: ${PFBUILD_DEB_STRETCH_IMG}:latest
  extends:
    - .build_job
    - .job_dev_triggers
    - .deb_script

# build_pkg jobs for release
build_pkg_release_centos_7:
  image: ${PFBUILD_CENTOS_7_IMG}:maintenance/${CI_COMMIT_TAG}
  extends:
    - .build_job
    - .job_release_triggers
    - .rpm_script

build_pkg_release_debian_stretch:
  image: ${PFBUILD_DEB_STRETCH_IMG}:maintenance/${CI_COMMIT_TAG}
  extends:
    - .build_job
    - .job_release_triggers
    - .deb_script

########################################
# BUILD_MAINTENANCE JOBS
########################################
# CI_COMMIT_REF_NAME contains maintenance/vX.X.X
build_maintenance_centos_7:
  image: ${PFBUILD_CENTOS_7_IMG}:${CI_COMMIT_REF_NAME}
  extends:
    - .maintenance_job
    - .job_maintenance_triggers

build_maintenance_debian_stretch:
  image: ${PFBUILD_DEB_STRETCH_IMG}:${CI_COMMIT_REF_NAME}
  extends:
    - .maintenance_job
    - .job_maintenance_triggers

########################################
# SIGN JOBS
########################################
sign:
  # only use when executor is docker
  image: buildpkg/debian:buster
  stage: sign
  script:
    - ci-sign-pkg
  dependencies:
    - build_pkg_dev_centos_7
    - build_pkg_dev_debian_stretch
    - build_pkg_release_centos_7
    - build_pkg_release_debian_stretch
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  # run job on runners tag with inverse.ca AND shell
  tags:
    - inverse.ca
    - shell
  extends:
    - .job_dev_and_release_triggers

########################################
# PUBLISH JOBS
########################################
pages:
  # only use when executor is docker
  image: buildpkg/debian:buster
  stage: publish
  variables:
    PAGES_DIR: public
    PAGES_HOST: gitlab.io
  environment:
    name: PPA
    url: http://${CI_PROJECT_NAMESPACE}.${PAGES_HOST}/${CI_PROJECT_NAME}
  script:
    - ci-pages-ppa
    - ci-pages-home
    - ci-pages-tree
  dependencies:
    - sign
  artifacts:
    expire_in: 1 day
    paths:
      - public
  # run job on runners tag with inverse.ca AND shell
  tags:
    - inverse.ca
    - shell
  extends:
    - .job_dev_and_release_triggers

########################################
# UPLOAD JOBS
########################################
deploy_rpm_dev:
  extends:
    - .deploy_rpm_job
    - .job_dev_triggers
  environment:
    name: devel/x86_64
    url: http://packetfence.org/downloads/PacketFence/RHEL7/${CI_ENVIRONMENT_NAME}

deploy_deb_dev:
  extends:
    - .deploy_deb_job
    - .job_dev_triggers
  environment:
    name: debian-devel
    url: http://packetfence.org/downloads/PacketFence/${CI_ENVIRONMENT_NAME}

deploy_rpm_release:
  extends:
    - .deploy_rpm_job
    - .job_release_triggers
  environment:
    name: x86_64
    url: http://packetfence.org/downloads/PacketFence/RHEL7/${CI_ENVIRONMENT_NAME}

deploy_deb_release:
  extends:
    - .deploy_deb_job
    - .job_release_triggers
  environment:
    name: debian-lastrelease
    url: http://packetfence.org/downloads/PacketFence/${CI_ENVIRONMENT_NAME}

