- hosts: dev
  name: install packetfence development packages
  become: True
  collections:
    - debops.debops
    - debops.roles01
    - debops.roles02
    - debops.roles03

  # workaround for https://github.com/ansible/ansible/issues/70304
  # to have ansible_distribution correct for bullseye
  pre_tasks:
    - name: Force cache update to get correct Ansible distribution release
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Refresh Ansible facts after cache update
      setup:
      when: ansible_os_family == 'Debian'

  roles:
    - role: inverse_inc.gitlab_buildpkg_tools
      tags: ci

    - role: apt_preferences
      when: ansible_os_family == 'Debian'
