- hosts: pfservers
  name: Set venom vars
  become: True
  gather_facts: True

  tasks:
  # packetfence-test or /usr/local/pf/t/venom/vars/local.yml should exist
  - import_tasks: tasks/install_venom_local_vars.yml
