- hosts: pfservers
  name: Set interfaces on hosts
  become: True
  gather_facts: True

  tasks:
    - name: add in grub config
      file:
        path: /etc/default/grub.d
        state: directory

    - name: add in grub config
      file:
        path: /etc/default/grub.d/original-interface-name.cfg
        state: touch

    - name: Ensure Interface is set to default
      ansible.builtin.lineinfile:
        path: /etc/default/grub.d/original-interface-name.cfg
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT net.ifnames=0"

    - name: Update grub
      ansible.builtin.shell: update-grub

    - name: add in eth0 file
      file:
        path: /etc/network/interfaces.d/eth0.conf
        state: touch

    - name: add content in eth0 config file
      blockinfile:
       path: /etc/network/interfaces.d/eth0.conf
       block: |
         auto eth0
         allow-hotplug eth0
         iface eth0 inet dhcp
