ignored = [
    "github.com/inverse-inc/packetfence/go/caddy/caddy",
    "github.com/inverse-inc/packetfence/go/caddy/caddy/caddyfile",
    "github.com/inverse-inc/packetfence/go/caddy/caddy/startupshutdown",
    "github.com/miekg/dns",
    "golang.org/x/net/context",
    "golang.org/x/net/context/ctxhttp",
    "golang.org/x/net/http2",
    "golang.org/x/net/http2/hpack",
    "golang.org/x/net/idna",
    "golang.org/x/net/internal/timeseries",
    "golang.org/x/net/lex/httplex",
    "golang.org/x/net/trace",
]

[[constraint]]
    name = "github.com/openzipkin/zipkin-go-opentracing"
    version = "v0.2.3"
