/config/device_registrations:
  description: pf::UnifiedApi::Controller::Config::DeviceRegistrations
  get:
    description: List items
    operationId: api.v1.Config::DeviceRegistrations.list
    parameters: []
    responses:
      '200':
        $ref: '#/components/schemas/config/DeviceRegistrationsList'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  post:
    description: Create an item
    operationId: api.v1.Config::DeviceRegistrations.create
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            properties:
              allowed_devices:
                description: List of OS which will be allowed to be register via the
                  self service portal.
                items:
                  description: List of OS which will be allowed to be register via
                    the self service portal.
                  type: string
                type: array
              category:
                description: The role to assign to devices registered from the specific
                  portal. If none is specified, the role of the registrant is used.
                type: string
              description:
                description: Description
                type: string
              id:
                description: Profile Name
                type: string
            required:
            - id
            type: object
