/config/floating_devices:
  description: Configure floating devices
  get:
    description: List items
    operationId: api.v1.Config::FloatingDevices.list
    parameters: []
    responses:
      '200':
        $ref: '#/components/schemas/config/FloatingDevicesList'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  post:
    description: Create an item
    operationId: api.v1.Config::FloatingDevices.create
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            properties:
              id:
                description: MAC Address
                type: string
              ip:
                description: IP Address
                type: string
              pvid:
                description: VLAN in which PacketFence should put the port
                type: integer
              taggedVlan:
                description: Comma separated list of VLANs. If the port is a multi-vlan,
                  these are the VLANs that have to be tagged on the port.
                type: string
              trunkPort:
                description: The port must be configured as a muti-vlan port
                type: string
            required:
            - id
            - pvid
            type: object
