/config/floating_device/{floating_device_id}:
  delete:
    description: Remove an item
    operationId: api.v1.Config::FloatingDevices.remove
    parameters: []
    responses:
      '204':
        description: Deleted a config item
  description: Configure floating devices
  get:
    description: Get an item
    operationId: api.v1.Config::FloatingDevices.get
    parameters: []
    responses:
      '200':
        $ref: '#/components/schemas/config/FloatingDevice'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  patch:
    description: Update an item
    operationId: api.v1.Config::FloatingDevices.update
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            properties:
              id:
                description: MAC Address
                type: string
              ip:
                description: IP Address
                type: string
              pvid:
                description: VLAN in which PacketFence should put the port
                type: integer
              taggedVlan:
                description: Comma separated list of VLANs. If the port is a multi-vlan,
                  these are the VLANs that have to be tagged on the port.
                type: string
              trunkPort:
                description: The port must be configured as a muti-vlan port
                type: string
            required:
            - id
            - pvid
            type: object
    responses:
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  put:
    description: Replace an item
    operationId: api.v1.Config::FloatingDevices.replace
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            properties:
              id:
                description: MAC Address
                type: string
              ip:
                description: IP Address
                type: string
              pvid:
                description: VLAN in which PacketFence should put the port
                type: integer
              taggedVlan:
                description: Comma separated list of VLANs. If the port is a multi-vlan,
                  these are the VLANs that have to be tagged on the port.
                type: string
              trunkPort:
                description: The port must be configured as a muti-vlan port
                type: string
            required:
            - id
            - pvid
            type: object
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
