---
/config/realm/{realm_id}:
  delete:
    parameters:
    - description: The tenant ID to use for this request. Can only be used if the
        API user has access to other tenants. When empty, it will default to use the
        tenant attached to the token.
      in: header
      name: X-PacketFence-Tenant-Id
      required: 0
      schema:
        type: string
    responses:
      '204':
        description: Deleted a config item
    summary: Delete a config item
  get:
    parameters:
    - description: The tenant ID to use for this request. Can only be used if the
        API user has access to other tenants. When empty, it will default to use the
        tenant attached to the token.
      in: header
      name: X-PacketFence-Tenant-Id
      required: 0
      schema:
        type: string
    requestBody:
      content:
        application/json:
          schema:
            properties:
              domain:
                description: The domain to use for the authentication in that realm
                type: string
              id:
                description: Realm
                type: string
              options:
                description: You can add options in the realm definition
                type: string
            required:
            - id
            type: object
      required: !!perl/scalar:boolean 1
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  patch:
    parameters:
    - description: The tenant ID to use for this request. Can only be used if the
        API user has access to other tenants. When empty, it will default to use the
        tenant attached to the token.
      in: header
      name: X-PacketFence-Tenant-Id
      required: 0
      schema:
        type: string
    requestBody:
      content:
        application/json:
          schema:
            properties:
              domain:
                description: The domain to use for the authentication in that realm
                type: string
              options:
                description: You can add options in the realm definition
                type: string
            required: []
            type: object
      required: !!perl/scalar:boolean 1
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  put:
    parameters:
    - description: The tenant ID to use for this request. Can only be used if the
        API user has access to other tenants. When empty, it will default to use the
        tenant attached to the token.
      in: header
      name: X-PacketFence-Tenant-Id
      required: 0
      schema:
        type: string
    requestBody:
      content:
        application/json:
          schema:
            properties:
              domain:
                description: The domain to use for the authentication in that realm
                type: string
              options:
                description: You can add options in the realm definition
                type: string
            required: []
            type: object
      required: !!perl/scalar:boolean 1
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
