/config/role/{role_id}:
  delete:
    description: Remove an item
    operationId: api.v1.Config::Roles.remove
    parameters: []
    responses:
      '204':
        description: Deleted a config item
  description: pf::UnifiedApi::Controller::Config::Roles
  get:
    description: Get an item
    operationId: api.v1.Config::Roles.get
    parameters: []
    responses:
      '200':
        $ref: '#/components/schemas/config/Role'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  patch:
    description: Update an item
    operationId: api.v1.Config::Roles.update
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            properties:
              id:
                description: Name
                type: string
              max_nodes_per_pid:
                description: The maximum number of nodes a user having this role can
                  register.
                type: integer
              notes:
                description: Description
                type: string
            required:
            - id
            - max_nodes_per_pid
            type: object
    responses:
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  put:
    description: Replace an item
    operationId: api.v1.Config::Roles.replace
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            properties:
              id:
                description: Name
                type: string
              max_nodes_per_pid:
                description: The maximum number of nodes a user having this role can
                  register.
                type: integer
              notes:
                description: Description
                type: string
            required:
            - id
            - max_nodes_per_pid
            type: object
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
