/config/syslog_parser/{syslog_parser_id}:
  delete:
    description: Remove an item
    operationId: api.v1.Config::SyslogParsers.remove
    parameters: []
    responses:
      '204':
        description: Deleted a config item
  description: pf::UnifiedApi::Controller::Config::SyslogParsers
  get:
    description: Get an item
    operationId: api.v1.Config::SyslogParsers.get
    parameters: []
    responses:
      '200':
        $ref: '#/components/schemas/config/SyslogParser'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  patch:
    description: Update an item
    operationId: api.v1.Config::SyslogParsers.update
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            discriminator:
              propertyName: type
            oneOf:
            - properties:
                id:
                  description: Detector
                  type: string
                path:
                  description: Alert pipe
                  type: string
                status:
                  description: Enabled
                  type: string
                type:
                  description: Type
                  type: string
              required:
              - id
              - path
              - type
              type: object
            - properties:
                id:
                  description: Detector
                  type: string
                path:
                  description: Alert pipe
                  type: string
                status:
                  description: Enabled
                  type: string
                type:
                  description: Type
                  type: string
              required:
              - id
              - path
              - type
              type: object
            - properties:
                id:
                  description: Detector
                  type: string
                loglines:
                  description: Loglines
                  type: string
                path:
                  description: Alert pipe
                  type: string
                rules:
                  description: Rules
                  items:
                    description: Rule - New
                    properties:
                      actions:
                        description: Actions
                        items:
                          description: Action
                          properties:
                            api_method:
                              description: Api method
                              type: string
                            api_parameters:
                              description: Api parameters
                              type: string
                          type: object
                        type: array
                      ip_mac_translation:
                        description: Perform automatic translation of IPs to MACs
                          and the other way around
                        type: string
                      last_if_match:
                        description: Stop processing rules if this rule matches
                        type: string
                      name:
                        description: Name
                        type: string
                      regex:
                        description: Regex
                        type: string
                    type: object
                  type: array
                status:
                  description: Enabled
                  type: string
                type:
                  description: Type
                  type: string
              required:
              - id
              - path
              - type
              type: object
            - properties:
                id:
                  description: Detector
                  type: string
                path:
                  description: Alert pipe
                  type: string
                status:
                  description: Enabled
                  type: string
                type:
                  description: Type
                  type: string
              required:
              - id
              - path
              - type
              type: object
            - properties:
                id:
                  description: Detector
                  type: string
                path:
                  description: Alert pipe
                  type: string
                status:
                  description: Enabled
                  type: string
                type:
                  description: Type
                  type: string
              required:
              - id
              - path
              - type
              type: object
            - properties:
                id:
                  description: Detector
                  type: string
                path:
                  description: Alert pipe
                  type: string
                status:
                  description: Enabled
                  type: string
                type:
                  description: Type
                  type: string
              required:
              - id
              - path
              - type
              type: object
            - properties:
                id:
                  description: Detector
                  type: string
                path:
                  description: Alert pipe
                  type: string
                status:
                  description: Enabled
                  type: string
                type:
                  description: Type
                  type: string
              required:
              - id
              - path
              - type
              type: object
    responses:
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  put:
    description: Replace an item
    operationId: api.v1.Config::SyslogParsers.replace
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            discriminator:
              propertyName: type
            oneOf:
            - properties:
                id:
                  description: Detector
                  type: string
                path:
                  description: Alert pipe
                  type: string
                status:
                  description: Enabled
                  type: string
                type:
                  description: Type
                  type: string
              required:
              - id
              - path
              - type
              type: object
            - properties:
                id:
                  description: Detector
                  type: string
                path:
                  description: Alert pipe
                  type: string
                status:
                  description: Enabled
                  type: string
                type:
                  description: Type
                  type: string
              required:
              - id
              - path
              - type
              type: object
            - properties:
                id:
                  description: Detector
                  type: string
                loglines:
                  description: Loglines
                  type: string
                path:
                  description: Alert pipe
                  type: string
                rules:
                  description: Rules
                  items:
                    description: Rule - New
                    properties:
                      actions:
                        description: Actions
                        items:
                          description: Action
                          properties:
                            api_method:
                              description: Api method
                              type: string
                            api_parameters:
                              description: Api parameters
                              type: string
                          type: object
                        type: array
                      ip_mac_translation:
                        description: Perform automatic translation of IPs to MACs
                          and the other way around
                        type: string
                      last_if_match:
                        description: Stop processing rules if this rule matches
                        type: string
                      name:
                        description: Name
                        type: string
                      regex:
                        description: Regex
                        type: string
                    type: object
                  type: array
                status:
                  description: Enabled
                  type: string
                type:
                  description: Type
                  type: string
              required:
              - id
              - path
              - type
              type: object
            - properties:
                id:
                  description: Detector
                  type: string
                path:
                  description: Alert pipe
                  type: string
                status:
                  description: Enabled
                  type: string
                type:
                  description: Type
                  type: string
              required:
              - id
              - path
              - type
              type: object
            - properties:
                id:
                  description: Detector
                  type: string
                path:
                  description: Alert pipe
                  type: string
                status:
                  description: Enabled
                  type: string
                type:
                  description: Type
                  type: string
              required:
              - id
              - path
              - type
              type: object
            - properties:
                id:
                  description: Detector
                  type: string
                path:
                  description: Alert pipe
                  type: string
                status:
                  description: Enabled
                  type: string
                type:
                  description: Type
                  type: string
              required:
              - id
              - path
              - type
              type: object
            - properties:
                id:
                  description: Detector
                  type: string
                path:
                  description: Alert pipe
                  type: string
                status:
                  description: Enabled
                  type: string
                type:
                  description: Type
                  type: string
              required:
              - id
              - path
              - type
              type: object
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
