/config/traffic_shaping_policies:
  description: pf::UnifiedApi::Controller::Config::TrafficShapingPolicies
  get:
    description: List items
    operationId: api.v1.Config::TrafficShapingPolicies.list
    parameters: []
    responses:
      '200':
        $ref: '#/components/schemas/config/TrafficShapingPoliciesList'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  post:
    description: Create an item
    operationId: api.v1.Config::TrafficShapingPolicies.create
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            properties:
              download:
                description: Bandwidth must be in the following format 'nXY' where
                  XY is one of the following KB,MB,GB,TB,PB
                type: string
              id:
                description: Role
                type: string
              upload:
                description: Bandwidth must be in the following format 'nXY' where
                  XY is one of the following KB,MB,GB,TB,PB
                type: string
            required:
            - id
            type: object
