---
packetfence_install__centos_release_rpm: "http://packetfence.org/downloads/PacketFence/RHEL8/packetfence-release-{{ pf_minor_release }}.el8.noarch.rpm"

# in localdev environment: we install from official repositories
packetfence_install__centos:
  repos:
    - packetfence

# override to installed test files
packetfence_install__centos_packages:
  - packetfence
  - packetfence-test

# override to installed test files
packetfence_install__deb_packages:
  - packetfence
  - packetfence-test
