---
- hosts: pfservers
  name: configure Packetfence VM
  become: True

  tasks:
    - name: Disable NetworkManager RHEL8
      ansible.builtin.service:
        name: NetworkManager
        state: stopped
        enabled: no
      when: ansible_facts['os_family'] == "RedHat"
