- hosts: service_rsyslog, service_dhcpd, service_freeradius, service_tinyproxy
  name: Update the apt cache
  become: True

  tasks:
    - name: Update APT repository cache
      apt:  # noqa no-handler
        update_cache: True

