- hosts: service_tinyproxy
  name: Manage Tinyproxy service
  become: True

  collections:
    - debops.debops
    - debops.roles01
    - debops.roles02
    - debops.roles03

  roles:
    - role: tinyproxy
