---
# Check if CI_COMMIT_TAG is defined (only when making a release) to disable devel repositories
# that contain install dependencies
release_status: '{{ True if lookup("env", "CI_COMMIT_TAG")
                         else False }}'

packetfence_install__centos:
  repo: '{{ "packetfence" if release_status|bool
                          else "packetfence-devel" }}'

packetfence_install__deb:
  repos: '{{ ["debian"] if release_status|bool
                        else ["debian","debian-devel"] }}'
