---
- hosts: pfservers
  name: Run dot1x_eap_peap tests
  become: True

  vars:
    test_suites:
      - configurator
      - global_config
      - wired_dot1x_eap_peap
      - wired_dot1x_eap_peap/teardown
      - wireless_dot1x_eap_peap
      - wireless_dot1x_eap_peap/teardown
      - global_teardown

  tasks:
    - name: Run Venom testsuites
      command: '/usr/local/pf/t/venom/venom-wrapper.sh /usr/local/pf/t/venom/test_suites/{{ item }}'
      args:
        chdir: '/usr/local/pf/t/venom'
      loop: '{{ test_suites }}'
      # add inventory__group_environment to Ansible environment
      # useful to make env vars available for Venom
      environment: '{{ inventory__group_environment | d({}) }}'

