---
pf_minor_release: '{{ lookup("env", "PF_MINOR_RELEASE") | default("99.9", true) }}'

packetfence_install__configurator_status: 'enabled'

packetfence_install__centos_release_rpm: "http://packetfence.org/downloads/PacketFence/RHEL8/packetfence-release-{{ pf_minor_release }}.el8.noarch.rpm"
packetfence_install__deb:
  repos:
    - 'debian/{{ pf_minor_release }}'
