- hosts: service_freeradius
  name: Manage FreeRADIUS service
  become: True

  collections:
    - debops.debops
    - debops.roles01
    - debops.roles02
    - debops.roles03

  roles:
    - role: freeradius
