- hosts: pfservers
  name: upgrade OS to latest version
  become: True
  gather_facts: True
  tags: upgrade
  collections:
    - debops.debops
    - debops.roles01
    - debops.roles02
    - debops.roles03

  tasks:
    - name: include distribution specific tasks
      include_tasks: "{{ ansible_os_family|lower }}.yml"
